import { jsPDF } from 'jspdf';

/**
 * Generates an enterprise-grade, 2-column structured DevOps migration report.
 * Uses direct jsPDF commands for high density and print-fidelity.
 */
export const generateProfessionalPDF = (data) => {
  if (!data) return;

  const doc = new jsPDF('p', 'mm', 'a4');
  
  // --- Constant Layout Config ---
  const MARGIN = 20;
  const PAGE_WIDTH = doc.internal.pageSize.getWidth();
  const PAGE_HEIGHT = doc.internal.pageSize.getHeight();
  const CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2);
  const COLUMN_GAP = 5;
  const COL_WIDTH = (CONTENT_WIDTH - COLUMN_GAP) / 2;
  const LEFT_X = MARGIN;
  const RIGHT_X = MARGIN + COL_WIDTH + COLUMN_GAP;
  const FOOTER_HEIGHT = 15;
  
  let currentY = 25;
  let leftY = currentY;
  let rightY = currentY;

  // --- Date/Timestamp ---
  const formattedDate = new Date().toLocaleDateString('en-GB', {
    day: '2-digit', month: 'long', year: 'numeric'
  });
  const timestamp = new Date().toLocaleString();

  // --- Helper: App ID ---
  const appId = (data.app_name || 'app').toUpperCase() + '-' + new Date().getTime().toString().slice(-6);

  // --- Helper: Draw Footer ---
  const drawFooter = () => {
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setDrawColor(200);
      doc.setLineWidth(0.2);
      doc.line(MARGIN, PAGE_HEIGHT - FOOTER_HEIGHT + 5, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - FOOTER_HEIGHT + 5);
      
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(`Generated by CloudMorph  |  ${timestamp}`, MARGIN, PAGE_HEIGHT - 10);
      
      const pageNum = `Page ${i} of ${totalPages}`;
      doc.text(pageNum, PAGE_WIDTH - MARGIN - doc.getTextWidth(pageNum), PAGE_HEIGHT - 10);
    }
  };

  // --- Helper: Global Page Break ---
  const triggerPageBreak = () => {
    doc.addPage();
    leftY = MARGIN + 10;
    rightY = MARGIN + 10;
    currentY = MARGIN + 10;
  };

  // --- Helper: Draw Compact Table ---
  const drawCompactTable = (title, items, x, y, width) => {
    const ROW_HEIGHT = 6;
    const PADDING = 3;
    const LABEL_WIDTH = width * 0.4;
    const VALUE_START_X = x + LABEL_WIDTH;
    const VALUE_WIDTH = width - LABEL_WIDTH - (PADDING * 2);

    // Measure total table height before drawing (for atomic page break)
    let totalTableHeight = 8; // Title space
    items.forEach(item => {
      const splitValue = doc.splitTextToSize(item.value || 'N/A', VALUE_WIDTH);
      const rowH = Math.max(ROW_HEIGHT, splitValue.length * 4.5);
      totalTableHeight += rowH + 2;
    });

    if (y + totalTableHeight > PAGE_HEIGHT - FOOTER_HEIGHT - 10) {
      triggerPageBreak();
      y = MARGIN + 10;
    }

    let localY = y;
    
    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(0);
    doc.setLineWidth(0.4);
    doc.text(title, x, localY);
    localY += 2;
    doc.setDrawColor(200);
    doc.line(x, localY, x + width, localY);
    localY += 6;

    // Body
    items.forEach(item => {
      const val = item.value || 'N/A';
      const splitValue = doc.splitTextToSize(val, VALUE_WIDTH);
      const rowHeight = Math.max(ROW_HEIGHT, splitValue.length * 4.5);
      
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text(item.label, x + 1, localY + 4);
      
      doc.setFont('helvetica', 'normal');
      doc.text(splitValue, VALUE_START_X + 1, localY + 4);
      
      doc.setLineWidth(0.1);
      doc.setDrawColor(220);
      localY += rowHeight + 2;
      doc.line(x, localY, x + width, localY);
    });

    return localY + 8; // Return new Y for this column
  };

  // --- 1. HEADER (Full Width) ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  const headerTitle = 'CLOUDMORPH MIGRATION REPORT';
  doc.text(headerTitle, (PAGE_WIDTH - doc.getTextWidth(headerTitle)) / 2, currentY);
  currentY += 4;
  doc.setLineWidth(0.8);
  doc.setDrawColor(0);
  doc.line(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY);
  currentY += 12;

  leftY = currentY;
  rightY = currentY;

  // --- 2. THE 2-COLUMN METADATA PHASE ---
  
  // Left Column Sections
  leftY = drawCompactTable('APPLICATION DETAILS', [
    { label: 'Platform ID', value: appId },
    { label: 'Application Name', value: data.app_name },
    { label: 'Tech Stack', value: data.stack },
    { label: 'Container Port', value: data.port?.toString() }
  ], LEFT_X, leftY, COL_WIDTH);

  leftY = drawCompactTable('INFRASTRUCTURE CONTEXT', [
    { label: 'Source Directory', value: data.source_path },
    { label: 'Dockerfile Entry', value: data.dockerfile_path },
    { label: 'Terraform Path', value: data.terraform_path }
  ], LEFT_X, leftY, COL_WIDTH);

  // Right Column Sections
  rightY = drawCompactTable('REPORT METADATA', [
    { label: 'Generated Date', value: formattedDate },
    { label: 'Timestamp', value: timestamp },
    { label: 'System Version', value: 'CloudMorph-v1.4.2' },
    { label: 'Data Integrity', value: 'VERIFIED' }
  ], RIGHT_X, rightY, COL_WIDTH);

  rightY = drawCompactTable('DEPLOYMENT CONFIG', [
    { label: 'Live Endpoint', value: data.deployment_url },
    { label: 'Registry Host', value: data.image_url },
    { label: 'Image Tag', value: data.image_name },
    { label: 'Deployment State', value: data.deployment_url ? 'SUCCESSFUL' : 'FAILED' }
  ], RIGHT_X, rightY, COL_WIDTH);

  // Reconciliation for switching back to full width
  currentY = Math.max(leftY, rightY) + 12;

  // --- 2.5 MIGRATION INTELLIGENCE (TRANSFORMATION & DEPENDENCIES) ---
  
  // A. Transformation Roadmap
  const roadmap = data.migration_summary || [];
  if (roadmap.length > 0) {
    const ROADMAP_HEIGHT = 15 + (roadmap.length * 8);
    if (currentY + ROADMAP_HEIGHT > PAGE_HEIGHT - FOOTER_HEIGHT) triggerPageBreak();

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.text('MIGRATION TRANSFORMATION ROADMAP', MARGIN, currentY);
    currentY += 3;
    doc.setLineWidth(0.3);
    doc.setDrawColor(210);
    doc.line(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY);
    currentY += 8;

    // Table Header
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text('COMPONENT / TIER', MARGIN + 2, currentY);
    doc.text('BASELINE (FROM)', MARGIN + 45, currentY);
    doc.text('OPTIMIZED (TO)', MARGIN + 90, currentY);
    doc.text('STATUS', MARGIN + 140, currentY);
    currentY += 2;
    doc.line(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY);
    currentY += 6;

    roadmap.forEach(item => {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(60);
      doc.text(item.component || 'N/A', MARGIN + 2, currentY);
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text(item.from || 'N/A', MARGIN + 45, currentY);
      
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text(item.to || 'N/A', MARGIN + 90, currentY);
      
      const status = (item.status || 'DONE').toUpperCase();
      const statusColor = status === 'UPGRADED' ? [59, 130, 246] : status === 'ADDED' ? [139, 92, 246] : [16, 185, 129];
      doc.setTextColor(...statusColor);
      doc.text(status, MARGIN + 140, currentY);
      
      currentY += 7;
      doc.setDrawColor(240);
      doc.setLineWidth(0.1);
      doc.line(MARGIN, currentY - 1, PAGE_WIDTH - MARGIN, currentY - 1);
    });
    currentY += 8;
  }

  // B. Dependency Audit
  const deps = data.dependencies || [];
  if (deps.length > 0) {
    const DEPS_HEIGHT = 15 + (deps.length * 7);
    if (currentY + DEPS_HEIGHT > PAGE_HEIGHT - FOOTER_HEIGHT) triggerPageBreak();

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.text(`DEPENDENCY AUDIT & ANALYSIS (${deps.length} PACKAGES)`, MARGIN, currentY);
    currentY += 3;
    doc.setLineWidth(0.3);
    doc.setDrawColor(210);
    doc.line(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY);
    currentY += 8;

    // Table Header
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text('PACKAGE NAME', MARGIN + 2, currentY);
    doc.text('VERSION', MARGIN + 60, currentY);
    doc.text('INSIGHT / STATUS', MARGIN + 110, currentY);
    currentY += 2;
    doc.line(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY);
    currentY += 6;

    deps.forEach(dep => {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(60);
      doc.text(dep.name || 'N/A', MARGIN + 2, currentY);
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text(dep.version || 'N/A', MARGIN + 60, currentY);
      
      const isActionable = dep.status === 'upgrade recommended';
      const statusText = isActionable ? 'UPGRADE SUGGESTED' : 'VERIFIED';
      const statusColor = isActionable ? [245, 158, 11] : [16, 185, 129];
      doc.setTextColor(...statusColor);
      doc.text(statusText, MARGIN + 110, currentY);
      
      currentY += 6;
      doc.setDrawColor(245);
      doc.line(MARGIN, currentY - 1, PAGE_WIDTH - MARGIN, currentY - 1);
    });
    currentY += 12;
  }

  doc.setTextColor(0);

  // --- 3. AUDIT SECTIONS (Full Width) ---
  
  // A. Migration Summary
  const summaryLog = (data.logs || []).find(log => log.startsWith('[SUMMARY]'));
  if (summaryLog) {
    if (currentY + 28 > PAGE_HEIGHT - FOOTER_HEIGHT) triggerPageBreak();
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.text('MIGRATION SUMMARY', MARGIN, currentY);
    currentY += 3;
    doc.setLineWidth(0.3);
    doc.setDrawColor(210);
    doc.line(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY);
    currentY += 8;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(80);
    const summaryText = summaryLog.replace('[SUMMARY]', '').trim();
    const splitSummary = doc.splitTextToSize(summaryText, CONTENT_WIDTH);
    doc.text(splitSummary, MARGIN, currentY);
    currentY += (splitSummary.length * 5) + 12;
    doc.setTextColor(0);
  }

  // B. Risks & Observations
  const riskLogs = (data.logs || []).filter(log => log.startsWith('[RISK_'));
  if (riskLogs.length > 0) {
    if (currentY + 35 > PAGE_HEIGHT - FOOTER_HEIGHT) triggerPageBreak();

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.text('RISKS & OBSERVATIONS', MARGIN, currentY);
    currentY += 3;
    doc.setLineWidth(0.3);
    doc.setDrawColor(210);
    doc.line(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY);
    currentY += 8;

    const sortedRisks = [...riskLogs].sort((a, b) => {
      const order = { '[RISK_HIGH]': 1, '[RISK_MEDIUM]': 2, '[RISK_LOW]': 3 };
      const aTag = (a.match(/\[RISK_(.*?)\]/) || [])[0];
      const bTag = (b.match(/\[RISK_(.*?)\]/) || [])[0];
      return (order[aTag] || 99) - (order[bTag] || 99);
    });

    sortedRisks.forEach(risk => {
      const severity = risk.includes('HIGH') ? 'HIGH' : risk.includes('MEDIUM') ? 'MEDIUM' : 'STABLE';
      const cleanRisk = risk.replace(/\[RISK_.*?\]/, '').trim();
      
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      const sevColor = severity === 'HIGH' ? [180, 0, 0] : severity === 'MEDIUM' ? [200, 100, 0] : [80, 80, 80];
      doc.setTextColor(...sevColor);
      doc.text(severity, MARGIN + 2, currentY);
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60);
      const splitRisk = doc.splitTextToSize(cleanRisk, CONTENT_WIDTH - 25);
      doc.text(splitRisk, MARGIN + 22, currentY);
      currentY += (splitRisk.length * 4.5) + 3;
    });
    currentY += 10;
  }

  // C. Manual Actions Required
  const manualLogs = (data.logs || []).filter(log => log.startsWith('[MANUAL]'));
  if (manualLogs.length > 0) {
    if (currentY + 30 > PAGE_HEIGHT - FOOTER_HEIGHT) triggerPageBreak();

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.text('MANUAL ACTIONS REQUIRED', MARGIN, currentY);
    currentY += 3;
    doc.setLineWidth(0.3);
    doc.setDrawColor(210);
    doc.line(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY);
    currentY += 8;

    manualLogs.forEach(action => {
      const cleanAction = action.replace('[MANUAL]', '').trim();
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(70);
      doc.text('•', MARGIN + 2, currentY);
      const splitAction = doc.splitTextToSize(cleanAction, CONTENT_WIDTH - 10);
      doc.text(splitAction, MARGIN + 8, currentY);
      currentY += (splitAction.length * 4.5) + 3;
    });
    currentY += 12;
    doc.setTextColor(0);
  }

  // --- 4. MIGRATION LOGS (Full Width) ---
  if (currentY + 30 > PAGE_HEIGHT - FOOTER_HEIGHT) triggerPageBreak();

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('MIGRATION TRACE LOGS', MARGIN, currentY);
  currentY += 4;
  doc.setLineWidth(0.4);
  doc.setDrawColor(200);
  doc.line(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY);
  currentY += 8;

  // Table Headers
  doc.setFontSize(9);
  doc.text('TYPE', MARGIN + 2, currentY);
  doc.text('EVENT MESSAGE', MARGIN + 32, currentY);
  currentY += 2;
  doc.setLineWidth(0.2);
  doc.line(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY);
  currentY += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const LOG_MSG_WIDTH = CONTENT_WIDTH - 35;

  (data.logs || []).forEach(log => {
    // Duplication Control: Filter out specifically handled audit tags
    if (log.startsWith('[SUMMARY]') || log.startsWith('[RISK_') || log.startsWith('[MANUAL]')) {
      return;
    }

    const match = log.match(/^\[(.*?)\]\s?(.*)$/);
    const type = match ? match[1].toUpperCase() : 'INFO';
    const msg = match ? match[2] : log;
    
    const splitMsg = doc.splitTextToSize(msg, LOG_MSG_WIDTH);
    const logItemHeight = (splitMsg.length * 4.5) + 3;

    if (currentY + logItemHeight > PAGE_HEIGHT - FOOTER_HEIGHT) {
      triggerPageBreak();
      // Re-draw log headers
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text('MIGRATION LOGS (CONTINUED)', MARGIN, currentY);
      currentY += 10;
      doc.setTextColor(0);
      doc.setFontSize(9);
      doc.text('TYPE', MARGIN + 2, currentY);
      doc.text('EVENT MESSAGE', MARGIN + 32, currentY);
      currentY += 2;
      doc.line(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY);
      currentY += 6;
      doc.setFont('helvetica', 'normal');
    }

    doc.text(type, MARGIN + 2, currentY);
    doc.text(splitMsg, MARGIN + 32, currentY);
    currentY += logItemHeight;
  });

  currentY += 10;

  // --- 4. AI INSIGHTS ---
  const aiLog = (data.logs || []).findLast(log => log.startsWith('[AI]'));
  if (aiLog) {
    const aiText = aiLog.replace('[AI]', '').trim();
    
    // Set font BEFORE splitting to ensure correct wrapping calculations
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10.5);

    const pageWidth = doc.internal.pageSize.getWidth();
    const marginLeft = 20;
    const marginRight = 20;
    const usableWidth = pageWidth - marginLeft - marginRight - 2; // 2mm safety buffer

    const lines = doc.splitTextToSize(aiText, usableWidth);
    const aiHeight = (lines.length * 5.5) + 18;

    if (currentY + aiHeight > PAGE_HEIGHT - FOOTER_HEIGHT) triggerPageBreak();

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('ARTIFICIAL INTELLIGENCE SUMMARY', marginLeft, currentY);
    currentY += 3;
    doc.setLineWidth(0.4);
    doc.setDrawColor(200);
    doc.line(marginLeft, currentY, pageWidth - marginRight, currentY);
    currentY += 8;

    // Render summary text
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10.5);
    doc.text(lines, marginLeft, currentY);
  }

  // --- FINALIZE ---
  drawFooter();
  doc.save(`cloudmorph-report-${data.app_name || 'app'}.pdf`);
};
